export enum CardType {
  FieldCard = 'FieldCard',
  TimelineCard = 'TimelineCard',
  TaskCard = 'TaskCard',
  NoteCard = 'NoteCard',
  FileCard = 'FileCard',
  EmailCard = 'EmailCard',
  CalendarCard = 'CalendarCard',
  WorkflowCard = 'WorkflowCard',
  WorkflowVersionCard = 'WorkflowVersionCard',
  WorkflowRunCard = 'WorkflowRunCard',
  RichTextCard = 'RichTextCard',
  OverviewCard = 'OverviewCard',
  AISuiteCard = 'AISuiteCard',
  PublicationDetailsCard = 'PublicationDetailsCard',
}
